
class Config:
    def getAccessToken(self):
        return 'EAAEIWZAUv1WkBAAeZCKChBzQZCWT7UJOVuKCOBEjafK8muL0B9PSaPFUzfFhPjajZCBVcAR1E5kurHqxkUUqlZBuqMLFnvWVBPaVg4zzQ3E82V8zyVSlmA1JlyYrnOen4j0qR6I1DwmrtlR8BTZBmugLMPJ93ahOB5MaYQU7g96AZDZD'
